import { JobSimulation, JobCategory, Difficulty } from '@/types';

export const JOB_SIMULATIONS: JobSimulation[] = [
  {
    id: 'data-analyst-sql',
    title: 'Data Analyst',
    description: 'Practice SQL queries and data analysis skills with real-world scenarios',
    category: JobCategory.DATA,
    difficulty: Difficulty.INTERMEDIATE,
    estimatedTime: 60,
    skills: ['SQL', 'Data Analysis', 'Problem Solving'],
    available: true,
    icon: '📊',
  },
  {
    id: 'frontend-engineer',
    title: 'Frontend Engineer',
    description: 'Build interactive UI components and solve frontend challenges',
    category: JobCategory.ENGINEERING,
    difficulty: Difficulty.INTERMEDIATE,
    estimatedTime: 90,
    skills: ['React', 'TypeScript', 'CSS'],
    available: false,
    icon: '💻',
  },
  {
    id: 'product-designer',
    title: 'Product Designer',
    description: 'Design user interfaces and solve UX problems',
    category: JobCategory.DESIGN,
    difficulty: Difficulty.INTERMEDIATE,
    estimatedTime: 75,
    skills: ['UI Design', 'UX Research', 'Prototyping'],
    available: false,
    icon: '🎨',
  },
  {
    id: 'marketing-analyst',
    title: 'Marketing Analyst',
    description: 'Analyze marketing data and create campaign strategies',
    category: JobCategory.MARKETING,
    difficulty: Difficulty.BEGINNER,
    estimatedTime: 45,
    skills: ['Analytics', 'Strategy', 'Communication'],
    available: false,
    icon: '📈',
  },
  {
    id: 'backend-engineer',
    title: 'Backend Engineer',
    description: 'Design APIs and solve backend system challenges',
    category: JobCategory.ENGINEERING,
    difficulty: Difficulty.ADVANCED,
    estimatedTime: 120,
    skills: ['Node.js', 'Databases', 'System Design'],
    available: false,
    icon: '⚙️',
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    description: 'Prioritize features and make product decisions',
    category: JobCategory.PRODUCT,
    difficulty: Difficulty.INTERMEDIATE,
    estimatedTime: 60,
    skills: ['Strategy', 'Analytics', 'Leadership'],
    available: false,
    icon: '🚀',
  },
];